### ISSUE TITLE
Improve Contact Me button and form

### ISSUE THREAD

**Issue by aanchal-fatwani** [swarajmhatre/swarajmhatre_portfolio#3]
@swarajmhatre  As part of HacktoberFest2023, I wish to improve the UI of the Contact Me button and form. 
Please assign this issue to me if you're fine accepting this issue for the improvement of this project and HacktoberFest submission.

**Comment by swarajmhatre** [comment]
Assigned! Go ahead.

**Comment by ankitmwd01** [comment]
please assign me this task

**Comment by aanchal-fatwani** [comment]
> Assigned! Go ahead.

Hi @swarajmhatre Could you please add me as assignee..
