### ISSUE TITLE
Improve UI for the main home section

### ISSUE THREAD

**Issue by aanchal-fatwani** [swarajmhatre/swarajmhatre_portfolio#4]
@swarajmhatre As part of HacktoberFest2023, I wish to improve the UI of the main section wherein currently the text is not coming properly and spanning over the image as well.
Please assign this issue to me if you're fine accepting this issue for the improvement of this project and HacktoberFest submission.

![image](https://github.com/swarajmhatre/swarajmhatre_portfolio/assets/63228776/5096ee37-9392-4f57-a6a7-bbcfe0b2546b)

**Comment by swarajmhatre** [comment]
Assigned! Go ahead.

**Comment by swarajmhatre** [comment]
After making a pull request. Email the screenshots of output to me.

**Comment by aanchal-fatwani** [comment]
> Assigned! Go ahead.

Hi @swarajmhatre Could you please add me as assignee..

**Comment by aanchal-fatwani** [comment]
Already seemed to be fixed by changes in previous PR, hence closing this issue.
